### ISSUE TITLE
scores_tst used both times in calibration_train_on_heldout() call in example.py

### ISSUE THREAD

**Issue by Jargonautika** [luferrer/CalibrationTutorial#1]
Hi, this is a very minor thing. When applying the code in example.py to my log posteriors (I was using the cross validation method because the dataset is small), I noticed on line 84 of example.py that the calibration_train_on_heldout function was called with scores_tst for the first two input arguments, and that the scores_tst_cal object created on line 80 is not used until line 94 when calculating the overall performance after calibration is applied. 

The expected_cost library's calibration.py file shows that the calibration_train_on_heldout function requires first logpost_tst which in example.py is scores_test and then second logpost_trn which in example.py is scores_tst_cal. I believe, then that line 84 should read:

`    _, calmodel = calibration_train_on_heldout(scores_tst, scores_tst_cal, targets_tst, `

**Comment by Jargonautika** [comment]
I just noticed that the same issue can be found in at least the 00_measure_perf_and_fix_calibration notebook in the Summary cell. It may be other places as well, as a heads up.

**Comment by luferrer** [comment]
That line is correct, the two arguments should be scores_tst. In fact, the first argument is not necessary because you ignore the calibrated scores created by that method, which is the first output and only keep the model trained on the second argument. 

The idea in that section is that, in the scenario where you only have test data, you would use the scores_tst_cal vector created with xval in line 80 to assess how calibrated or miscalibrated your system is. Now, if the calloss computed in line 95 tells you that your system was miscalibrated, you would need a calibration model to deploy. But with xval you obtained several models, not just one. So, line 84 trains a single calibration model on all your test data. That is the model you would deploy. 

I hope that helps, otherwise let me know.

**Comment by Jargonautika** [comment]
Oh, ok, that makes sense to me. I see now that the `logpostcal` object that comes back from `calibration_train_on_heldout` is expected to be optimistic/optimal because that singular model (not the nfolds cross-validated models) has been trained and tested on all of the same data. I hadn't understood what you meant by "cheating calibration", but your explanation has helped that click for me. The model from `calibration_train_on_heldout` is only for use on other external test sets / deployment. Thanks!
